server:

# ------------------------------------------------------------
# Oficio: Ofício nº 16680240 – CyberGaeco
# Gerado em: 30/05/2026
# Regras: 6
# ------------------------------------------------------------
local-zone: "filmeamanhecer.com" always_refuse
local-zone: "menaseries.org" always_refuse
local-zone: "nossoplayeronlinehd.ink" always_refuse
local-zone: "themegaflix.com" always_refuse
local-zone: "torrentdosfilmes1.site" always_refuse
local-zone: "tvmega.online" always_refuse

# ------------------------------------------------------------
# Oficio: Oficio_16655322_CyberGaeco.pdf
# Gerado em: 30/05/2026
# Regras: 4
# ------------------------------------------------------------
local-zone: "filmesparadownload.org" always_refuse
local-zone: "thecinevision.com.br" always_refuse
local-zone: "visioncinevs.com" always_refuse
local-zone: "webcinevs.com" always_refuse

